project:
  type: website

website:
  title: "DevOps"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - project2.qmd
      - project3.qmd
      - project4.qmd
      - eda.qmd
      - model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

